### ISSUE TITLE
Event / Class Manager Confirms Booking

### ISSUE THREAD

**Issue by BeMyTv** [Intermezzon/palms.academy#122]
The confirmation page where managers approve whether an employee can join the class or event would be clearer if the menu with the approve / deny button was visible immediately upon entering the page.

Currently, you need to select a person before it appears.

https://github.com/user-attachments/assets/40d6f38a-385f-4543-bfdc-3d26562f3146

**Comment by onnerby** [comment]
First fix: Show buttons always but disable them when no one is selected.
Later fix: Add action buttons for each row: Check and "X"
