### ISSUE TITLE
Event calendar

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#15]
**Is your feature request related to a problem? Please describe.**
It's hard to know what upcoming events that are planed that the user can sign up for.

**Describe the solution you'd like**
Some kind of kalender och list of all upcoming events in the course catalog or on the start page would be useful, so the user can quickly find what to sign up for in the near future

**Comment by onnerby** [comment]
First sketches from out designers is a draft on the widget for the startpage that looks like this
![image](https://github.com/Intermezzon/palms.academy/assets/1788794/3a5f3167-a833-45ac-b0fe-dfa9b612c248)
![image](https://github.com/Intermezzon/palms.academy/assets/1788794/4e6a7152-d5bd-4e70-892b-3ff7bdf9c3bd)
Please note that this is just a first draft in order for us to iterate forward.

**Comment by certifikation** [comment]
Tack för att ni delade de första skisserna på widgeten för startsidan.! Skissen ser bra ut och jag gillar det övergripande utseendet. Dock det vore fördelaktigt om användaren kan anpassa vilken information som visas på startsidan. Det skulle ge användaren en mer personlig och anpassad upplevelse. 
Återigen, tack för ert arbete och jag ser fram emot att se hur ni kan förbättra och anpassa widgeten ytterligare!

**Comment by wearerobots** [comment]
Additional designs for the catalog page.
Please note these designs are drafts and prototypes and are subject to change before they are released.

### Desktop
![Calendar catalog 3 - desktop-1](https://github.com/Intermezzon/palms.academy/assets/6368984/0efc8e87-9dd6-4772-89bb-c69339df10d2)
![Calendar catalog 3 - desktop-2](https://github.com/Intermezzon/palms.academy/assets/6368984/f6caec70-7ffc-4dfb-a967-0080c2362859)

https://github.com/Intermezzon/palms.academy/assets/6368984/42e52cf4-7dd8-4ce8-9a27-ab268c49f183

### Mobile
![Calendar catalog 3 - iPhone 14   15 Pro - 1](https://github.com/Intermezzon/palms.academy/assets/6368984/ea14b88d-d9f4-4457-9c61-b60bb2eb22d8)
![Calendar catalog 3 - iPhone 14   15 Pro - 2](https://github.com/Intermezzon/palms.academy/assets/6368984/19cc833f-10a5-41d7-90b3-4493caf34188)

https://github.com/Intermezzon/palms.academy/assets/6368984/8901cdc8-ba7a-4c72-a84f-e5be69312878

**Comment by HannaHumana** [comment]
Var är det jag ser deadline datum för varje issue?

**Comment by Sterd** [comment]
> Var är det jag ser deadline datum för varje issue?

Hej @HannaHumana, du ser dem här: https://github.com/orgs/Intermezzon/projects/6/views/2

**Comment by HannaHumana** [comment]
Tack Per :)

Hur var det nu, behöver jag klicka på varje issue och välja prenumerera för
att få mail när det är en uppdatering i ärendet?
