### ISSUE TITLE
Create Google Meet occasions

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#16]
**Is your feature request related to a problem? Please describe.**
Just like the Microsoft Teams integration - we need to be able to create Google Meet from the markdown editor

**Comment by onnerby** [comment]
This feature is almost done. This is how it currently looks like

https://github.com/Intermezzon/palms.academy/assets/1788794/e8e77124-6967-4dea-a73a-0165ccdbebc1

**Comment by HannaHumana** [comment]
Hej,

Vem på it är det som slutför så att knappen fungerar och vet ni när dom gör
det?


*Hanna Marinadotter* | Course coordinator
***@***.***

Warfvinges väg 39 | 112 51 Stockholm
Växel: 08-599 299 00 |  www.humana.se
Följ oss på Facebook <https://www.humana.se/socialmedia> Linkedin
<https://www.linkedin.com/company/humana-ab>


------------------------------

*Om du inte är den rätta mottagaren till detta meddelande ber vi dig att*
*omgående underrätta oss och sedan radera meddelandet från din dator,*
*utan att behålla kopior eller informera om innehållet till andra personer.*
*Tack på förhand.*

*När du skickar e-post till Humana behandlar vi personuppgifter*
*såsom namn och e-postadress samt de personuppgifter du*
*väljer att lämna till oss i e-postmeddelandet.*

Så här behandlar vi personuppgifter
<https://www.humana.se/om-humana/behandling-av-personuppgifter/>


Den mån 27 maj 2024 kl 09:19 skrev Daniel Önnerby ***@***.***

**Comment by HannaHumana** [comment]
Andreas på it hade glömt att höra av sig eller be nån på it. Han undersöker
vidare och jag har bett dom skynda sig

*Hanna Marinadotter* | Course coordinator
***@***.***

Warfvinges väg 39 | 112 51 Stockholm
Växel: 08-599 299 00 |  www.humana.se
Följ oss på Facebook <https://www.humana.se/socialmedia> Linkedin
<https://www.linkedin.com/company/humana-ab>


------------------------------

*Om du inte är den rätta mottagaren till detta meddelande ber vi dig att*
*omgående underrätta oss och sedan radera meddelandet från din dator,*
*utan att behålla kopior eller informera om innehållet till andra personer.*
*Tack på förhand.*

*När du skickar e-post till Humana behandlar vi personuppgifter*
*såsom namn och e-postadress samt de personuppgifter du*
*väljer att lämna till oss i e-postmeddelandet.*

Så här behandlar vi personuppgifter
<https://www.humana.se/om-humana/behandling-av-personuppgifter/>


Den mån 27 maj 2024 kl 09:19 skrev Daniel Önnerby ***@***.***
