### ISSUE TITLE
Booking form external participants

### ISSUE THREAD

**Issue by MarieEklund** [Intermezzon/palms.academy#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- Text:
    - Om du har skyddade personuppgifter, kontakta utbildaren så hjälper vi dig hur du ska gå tillväga
    - Information that the booking form is only for participants outside Humana
- Add two squares for consent:
    - That the person agrees upon geeting marketing from Humana (yes/no)
    - That the person has read Humanas "integritetspolicy"

**Describe alternatives you've considered**

**Additional context**

**Comment by onnerby** [comment]
This is a custom function for you, so I have made this a internal issue on your board instead.
