### ISSUE TITLE
Report: List users with extended rights

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#36]
**Is your feature request related to a problem? Please describe.**
We need to get a list of all users that have some kind of extended rights lite "content creator" or "super user" 

**Describe the solution you'd like**
A filter in the report tool where you both can see and filter the extended rights

**Comment by HannaHumana** [comment]
> **Is your feature request related to a problem? Please describe.** We need to get a list of all users that have some kind of extended rights lite "content creator" or "super user"
> 
> **Describe the solution you'd like** A filter in the report tool where you both can see and filter the extended rights

Also get a report of education owners (don't remember if we have a ticket for this already?) Name of owner, course name, course link would be great

**Comment by wearerobots** [comment]
@HannaHumana Great news! You can already do this using our report tool. If you need some help getting started, our support is always happy to assist you. Just reach out and we'll be glad to walk you through the process: support@intermezzon.com
