### ISSUE TITLE
Sync boss over several teams

### ISSUE THREAD

**Issue by HannaHumana** [Intermezzon/palms.academy#60]

**Comment by onnerby** [comment]
Is this a feature request or a bug report?  Please use the provided templates.
Please note that issues are public and visible to everyone.

**Comment by HannaHumana** [comment]
This is an issue we have talked about but I can’t see that you have added
it. It’s about looking at the sync and see if it’s possible to sync so that
a boss that is boss for several teams automatically will be a boss for
several teams in lärportalen. We can talk about it shortly in the meeting.


*Hanna Marinadotter* | Course coordinator
***@***.***

Warfvinges väg 39 | 112 51 Stockholm
Växel: 08-599 299 00 |  www.humana.se
Följ oss på Facebook <https://www.humana.se/socialmedia> Linkedin
<https://www.linkedin.com/company/humana-ab>


------------------------------

*Om du inte är den rätta mottagaren till detta meddelande ber vi dig att*
*omgående underrätta oss och sedan radera meddelandet från din dator,*
*utan att behålla kopior eller informera om innehållet till andra personer.*
*Tack på förhand.*

*När du skickar e-post till Humana behandlar vi personuppgifter*
*såsom namn och e-postadress samt de personuppgifter du*
*väljer att lämna till oss i e-postmeddelandet.*

Så här behandlar vi personuppgifter
<https://www.humana.se/om-humana/behandling-av-personuppgifter/>


tis 14 maj 2024 kl. 09:25 skrev Daniel Önnerby ***@***.***>:

**Comment by onnerby** [comment]
This might be the same as #61, but lets discuss on our next meeting

**Comment by HannaHumana** [comment]
Yes that might be it. We couldn’t find it but the list is pretty long 😅


*Hanna Marinadotter* | Course coordinator
***@***.***

Warfvinges väg 39 | 112 51 Stockholm
Växel: 08-599 299 00 |  www.humana.se
Följ oss på Facebook <https://www.humana.se/socialmedia> Linkedin
<https://www.linkedin.com/company/humana-ab>


------------------------------

*Om du inte är den rätta mottagaren till detta meddelande ber vi dig att*
*omgående underrätta oss och sedan radera meddelandet från din dator,*
*utan att behålla kopior eller informera om innehållet till andra personer.*
*Tack på förhand.*

*När du skickar e-post till Humana behandlar vi personuppgifter*
*såsom namn och e-postadress samt de personuppgifter du*
*väljer att lämna till oss i e-postmeddelandet.*

Så här behandlar vi personuppgifter
<https://www.humana.se/om-humana/behandling-av-personuppgifter/>


tis 14 maj 2024 kl. 14:15 skrev Daniel Önnerby ***@***.***>:

**Comment by onnerby** [comment]
Same as #61
