### ISSUE TITLE
Not having to do over all quiz questions when one answer is incorrect

### ISSUE THREAD

**Issue by HannaHumana** [Intermezzon/palms.academy#67]
Example gdpr education. Having to answer all questions again and again.

**Comment by onnerby** [comment]
What it the suggested solution for this?
If the users get feedback on what they have answered right and wrong - shouldn't they know what to answer the second time?

**Comment by HannaHumana** [comment]
I think the solution suggested is that they don’t have to do the correctly
answered questions again in the next round, just the incorrect answers.
Gdpr has a lot of quiz questions so the participants get confused and
struggle with remembering.
