### ISSUE TITLE
Notification on cancelled or edited events

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#7]
When an event occasion is cancelled there is only a email send out to the users.
This should be a calendar cancelation so that it's removed from the users calendars.

The same when a occasion is updated. Right now the users do not get any updated calendar invitation.

**Comment by jariojasti** [comment]
Just wondering on how we should follow the progress of the issue. Is there a kanban table to see the progress or some other follow up functionality in github?

**Comment by onnerby** [comment]
This issue is now solved and will go live next week.
There is one remaining issue regarding canceling a whole occasion that we have created a own issue about.
