### ISSUE TITLE
Event "status booked"

### ISSUE THREAD

**Issue by BeMyTv** [Intermezzon/palms.academy#91]
If a person registers for an event session, the status of the event activity does not change until the event has taken place. There should be an "orange" status, such as "booked" or something similar, so that one can quickly analyze who has booked.

It would also be useful if you want to create an automation that sends a reminder to register for the event, for example, 5 days after they gain access to the activity. You wouldn’t want to send this reminder to those who have already booked.

**Comment by onnerby** [comment]
Status
 - When booked - WAITING (but text "Booked")
 - When occasion started - STARTED
 - When occasion end date passed - PASSED (if automatic)
