### ISSUE TITLE
Summary after quiz

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#98]
**Is your feature request related to a problem? Please describe.**
When you are done with a quiz, we need the system to give feedback on what when right/wrong without revealing the answers - in order for the learner to learn.

**Describe the solution you'd like**
Summary on tags and competences, like:
 - #Sales Failed - 3/5 (60%) with 80% required
 - #Support Success - 4/4 (100%) with 80% required

**Comment by certifikation** [comment]
- It could be beneficial to add a feature that supports providing feedback in text form after a quiz has been either passed or failed.

To provide support for scenarios such as:
- Sales: Failed - 3/5 (60%)
- Support: Success - 4/4 (100%)

- To visualize the results using charts and graphs, such as bar charts.

**Comment by onnerby** [comment]
The summary is taking shape and will look something like this
![image](https://github.com/user-attachments/assets/918610fe-98c8-4d7c-b810-b7e989d0c764)
It will also be possible to specify what will be visible in the administration
![image](https://github.com/user-attachments/assets/0be20c75-acb4-4a1a-aa00-2e431ecad915)

**Comment by onnerby** [comment]
This is now live 🎉
